FROM golang:1.25 AS build

COPY go.mod go.sum /src/
COPY web /src/web

ENV CGO_ENABLED=0
RUN cd /src && go build -o /web web/main.go

FROM alpine:3.20

COPY --from=build /web /web
COPY --from=build /src/web/templates /templates

ENTRYPOINT [ "/web" ]